require 'rake'
require 'rake/clean'
require 'webrick'

task :default => :serve

task :serve => :build do
  WEBrick::HTTPServer.new(:DocumentRoot => "./", :Port => 8000).start
end

task :build do
  sh 'elm-make --yes phonecat.elm --output phonecat.js'
end

CLEAN << "elm-stuff" << "elm-package.json"
